

CGLIB := libCaloGraphy.so
CGG4LIB := libCGG4.so


CXX := g++
DEPFLAGS := -MD -MP
DBG := -g

CXXFLAGS := -I../calography/
G4CSSFLAGS := 

CGSRC :=  node.cc process.cc track.cc
G4SRC := CGG4Interface.cc


.PHONY: clean all

all: $(CGLIB) $(CGG4LIB)


# build the calography base package
$(CGLIB): 

# build the Geant4 interface
$(CGG4LIB):


clean:

